### ISSUE TITLE
New Swag system interface.

### ISSUE THREAD

**Issue by c3c1l1a** [tunapanda/wp-swag#2]
Redesign of the interface with the landing page being a subset of the map with a compulsory entry Swagpath to walk a new user through the system and how to use it. 
- The system should just a subset of the next level of possible paths that the learner can follow. 
- If a Swagpath has previous dependencies, the path to them should appear even if the learner hasn't gone through them. 
- Pop up a window when a Swagpath is completed indicating the badge earned and points.
- Redesign the badges page.

**Comment by limikael** [comment]
how's it looking now?
