### ISSUE TITLE
"Hack" timeline and course presentation completion

### ISSUE THREAD

**Issue by limikael** [tunapanda/wp-swag#9]
_From @limikael on February 24, 2016 16:8_

Create some hack for now, so we can identify completion of timeline content, and also check actual completion of course presentation the way we want it to work, while we wait for the fix from H5P.

_Copied from original issue: tunapanda/TI-wp-content-theme#57_

**Comment by limikael** [comment]
A workaround for this: https://github.com/tunapanda/TI-wp-content-theme/issues/33

**Comment by limikael** [comment]
The completion of swagpaths work like this now:
- If the swagpath has questions, they need to be answered and need to be correct, and the learner needs to go to the last slide.
- If the swagpath has no questions, the learner just needs to go to the last slide.

**Comment by munga4** [comment]
Working well.
